import type { ParamSchema } from '@/visualizations/types';

export const monolithParams = {
  bars: 256,
  spacing: 0.04,
  width: 0.04,
  maxHeight: 3.5,
  threshold: 0.04,
  scrollSpeed: 0.08,
  rotateY: 0,
  brightness: 0.6,
  smooth: 0.35,
  freqLow: 0,
  freqHigh: 1.0,
  baseColor: '#f4f4f4',
  peakColor: '#bfe5ff',
  invertY: false,
};

export type MonolithParams = typeof monolithParams;

export const monolithSchema: ParamSchema = {
  bars: {
    type: 'range',
    label: { zh: '柱数', en: 'Bars' },
    min: 32,
    max: 512,
    step: 1,
    group: 'GEOMETRY',
  },
  spacing: {
    type: 'range',
    label: { zh: '间距', en: 'Spacing' },
    min: 0.01,
    max: 0.2,
    step: 0.005,
    group: 'GEOMETRY',
  },
  width: {
    type: 'range',
    label: { zh: '柱宽', en: 'Width' },
    min: 0.01,
    max: 0.15,
    step: 0.005,
    group: 'GEOMETRY',
  },
  maxHeight: {
    type: 'range',
    label: { zh: '最大高度', en: 'Max Height' },
    min: 1,
    max: 12,
    step: 0.1,
    group: 'GEOMETRY',
  },
  threshold: {
    type: 'range',
    label: { zh: '亮度阈值', en: 'Threshold' },
    min: 0,
    max: 0.4,
    step: 0.005,
    group: 'COLOR',
  },
  brightness: {
    type: 'range',
    label: { zh: '辉度', en: 'Brightness' },
    min: 0.2,
    max: 2.5,
    step: 0.05,
    group: 'COLOR',
  },
  smooth: {
    type: 'range',
    label: { zh: '响应平滑', en: 'Smooth' },
    min: 0.05,
    max: 0.8,
    step: 0.01,
    group: 'MOTION',
  },
  scrollSpeed: {
    type: 'range',
    label: { zh: '横移速度', en: 'Scroll Speed' },
    min: -1,
    max: 1,
    step: 0.01,
    group: 'MOTION',
  },
  rotateY: {
    type: 'range',
    label: { zh: '俯转角', en: 'Rotate Y' },
    min: -1,
    max: 1,
    step: 0.01,
    group: 'MOTION',
  },
  freqLow: {
    type: 'range',
    label: { zh: '低频起点', en: 'Freq Low' },
    min: 0,
    max: 0.9,
    step: 0.01,
    group: 'MOTION',
  },
  freqHigh: {
    type: 'range',
    label: { zh: '高频终点', en: 'Freq High' },
    min: 0.1,
    max: 1,
    step: 0.01,
    group: 'MOTION',
  },
  baseColor: {
    type: 'color',
    label: { zh: '基色', en: 'Base Color' },
    group: 'COLOR',
  },
  peakColor: {
    type: 'color',
    label: { zh: '峰值色', en: 'Peak Color' },
    group: 'COLOR',
  },
  invertY: {
    type: 'toggle',
    label: { zh: '倒置', en: 'Invert' },
    group: 'GEOMETRY',
  },
};
